# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-26 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
