# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-26 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0002_photo_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
    ]
